### ISSUE TITLE
kube-deployment.yml: error converting YAML to JSON: yaml: line 92: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Rabieezz** [dockersamples/docker-fifth-birthday#38]
I am using Docker Desktop to run the voting app, I am following the [tutorial](https://birthday.play-with-docker.com/kubernetes-docker-desktop/)  the link in the command line is deprecated  : 

```
kubectl apply -f https://raw.githubusercontent.com/docker/docker-birthday/master/resources/kubernetes-docker-desktop/vote.yaml
```

So I tried to use the link from this repo : 

```
kubectl apply -f https://github.com/dockersamples/docker-fifth-birthday/blob/master/kubernetes-desktop/kube-deployment.yml
```

But this error keeps on popping : 
```
error: error parsing https://github.com/dockersamples/docker-fifth-birthday/blob/master/kubernetes-desktop/kube-deployment.yml: error converting YAML to JSON: YAML: line 92: mapping values are not allowed in this context
```

```YAML

---
apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: LoadBalancer
  ports:

```
what am I doing wrong?
