### ISSUE TITLE
Kubernetes on Docker for Windows example needs specific Kubernetes Manifest

### ISSUE THREAD

**Issue by david-maumenee** [dockersamples/docker-fifth-birthday#6]
I tried to deploy [kube-deployment.yml](https://github.com/dockersamples/docker-fifth-birthday/blob/master/kubernetes-desktop/kube-deployment.yml) with Kubernetes on Docker for Windows  18.03.0-ce-rc4.
The DB pod is on error :
```
kubectl logs -f db-6488476b5-25gs9
...
state:
      waiting:
        message: 'Error response from daemon: invalid mode: /var/lib/postgresql/data'
        reason: CreateContainerError
```
The issue comes from the persistent Volume Claim 
```
kubectl get pv --output=yaml
...
hostPath:
      path: C:\Users\d.maumenee/.docker/Volumes/postgres-pv-claim/pvc-5a21cf61-2957-11e8-a980-00155d4b0118
```
By default, the volume is mapped on my windows file system but according to [docker for windows documentation](https://docs.docker.com/docker-for-windows/#shared-drives), it's can rise issues : 
*If possible, avoid volume mounts from the Windows host, and instead mount on the MobyVM, or use a data volume (named volume) or data container. There are a number of issues with using host-mounted volumes and network paths for database files.*
There is already an [issue](https://github.com/docker/for-win/issues/1758) declared on docker/for-win github

I didn't manage to change the behavior of the default storageClass.

To deploy on Docker for Windows I use this work around in the db deployment :
```
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          hostPath:
            path: /tmp/postgres-data
            type: DirectoryOrCreate
```
It works only on single node cluster, but Kubernetes integrate in Docker for Windows is exactly a single node cluster.

See kube-deployment-volume-without-claim.yml in pull request #7 

Docker version : 18.03.0-ce-rc4-win57 (16511)
Windows 10 Pro 1703 (build 15063.850)
